### ISSUE TITLE
stream video while playing a directory of music

### ISSUE THREAD

**Issue by hurnhu** [scivision/PyLivestream#12]
is it possible to play a video and also sen entire directory of music?

**Comment by scivision** [comment]
Yes:

Example: stream all .mp3 audio in `~/music` with an animated GIF or video clip repeating:

    python FileGlobLivestream.py ~/music youtube -glob "*.mp3" -image myclip.avi
    
or

    python FileGlobLivestream.py ~/music youtube -glob "*.mp3" -image animated.gif
