### ISSUE TITLE
Not able to stream live on youtube

### ISSUE THREAD

**Issue by SagarVirpara** [scivision/PyLivestream#18]

**Comment by fspider** [comment]
Hello!
Can you show me sample code which stream live from youtube?
This is Youtube live stream URL https://youtu.be/17Deeq8N2e4

I have been coded with videgear library. But i can't get resolution and fps before streaming
Is this possible with Pylivestream?
If the please Share you example code.

# import libraries
from vidgear.gears import CamGear
import cv2

stream = CamGear(source='https://youtu.be/17Deeq8N2e4', y_tube = True, logging=True).start() # YouTube Video URL as input

# infinite loop
while True:
	frame = stream.read()

**Comment by scivision** [comment]
https://github.com/scivision/PyLivestream/blob/master/pylivestream/utils.py#L90

which uses FFprobe JSON output. It assumes there's only one video stream and uses its parameters--here, the resolution
