### ISSUE TITLE
24/7 Youtube music stream

### ISSUE THREAD

**Issue by ohld** [scivision/PyLivestream#20]
Hi! I just found your project and it looks awesome! 

Is it possible to create 24/7 audio music stream 
(grab `*.mp3` from folder or internet audio stream and set some `*.png` or `*.gif` as an 'video')
with your library? And push it all to Youtube? 

If yes - can you please describe how can this be deployed? I'd very like to run all of this on my raspberry pi. 

Thanks! And great job!

**Comment by scivision** [comment]
Yes the command would be like:
```sh
FileGlobLivestream /home/user/myaudio youtube -glob "*.mp3" -image myimg.png
```

**Comment by ohld** [comment]
Thanks! I'll try it. 
How should I login into youtube?

**Comment by scivision** [comment]
https://www.youtube.com/live_dashboard

at the bottom is "encoder setup" that gives you the secret code to put into the file `youtube.key` which is in the same directory as `stream.ini`
