### ISSUE TITLE
A youtube stream example?

### ISSUE THREAD

**Issue by elieobeid7** [scivision/PyLivestream#21]
There's no tutorial for this library nor documentation, all I have is a readme, it's not clear to me where to put the file `youtube.key`, should I put it in the same directory of my project? Should I call it anything or just put the key in an empty file?

Is it possible to provide the simplest working example of how to stream to youtube, like a getting started script which one could use as a template?

**Comment by scivision** [comment]
Thank you, a tutorial is clearly needed.

The way I usually use PyLivestream is to have the Git repo cloned to a directory. By default, the scripts like Microphone.py look for `*.key` files like `youtube.key` in the same directory.

For example, if I have directory `~/pylivestream/` with Microphone.py *et al* there, then by default you should have `~/pylivestream/youtube.key` and other key files you might use.

The names of the keyfiles can be arbitrary, they are set in `stream.ini`.

So if I was just getting started, I would create a file `youtube.key` under ~/pylivestream or wherever the top-level scripts are (Microphone.py, Webcam.py etc) that contains nothing more than the random string given to you by YouTube Live streaming interface.

**Comment by elieobeid7** [comment]
Awesome thanks so much.
