### ISSUE TITLE
stream videos 24*7 on youtube offline

### ISSUE THREAD

**Issue by joseph488** [scivision/PyLivestream#22]
I need to know how to stream or go live to youtube with a downloaded or recorded video 24*7 but without turning the computer on for 24 hours (i.e offline).......Please help..its urgent

**Comment by scivision** [comment]
That would have to be done via a cloud-based server streaming to YouTube but the costs would be significant. Better to just upload a video as usual to YouTube. Or otherwise have an off-site computer that is on continuously to stream
