### ISSUE TITLE
ModuleNotFoundError: No module named 'Screenshare'

### ISSUE THREAD

**Issue by taewookim** [scivision/PyLivestream#24]
Python 3.7 (Conda)
Windows/Cygwin
ffmpeg version N-87130-g2b9fd15 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 7.1.0 (GCC)

Steps taken
1) pip install PyLivestream
2) Went to test page where I want to live stream and go the stream key, copied in facebook.key
3) From that facebook.key folder, i ran ScreenshareLivestream facebook. Then got this error

Seems to be pythonpath issue(?)

**Comment by scivision** [comment]
Yes you may have installed in cygwin instead of native windows.

Try 
```
python -m pip install pylivestream
```

**Comment by scivision** [comment]
This was resolved in v1.9.2 https://github.com/scivision/PyLivestream/releases  Thanks!
