### ISSUE TITLE
Running PyLivestream command

### ISSUE THREAD

**Issue by dreamGoAndHaveFun** [scivision/PyLivestream#27]
### Hey,

I guess I'm missing something, I didn't succeed to run your beautiful project on a Raspberry Pi 3 model B+ running raspbian...

I tried with pip :
`python3 -m pip install PyLivestream`
_('3' is required, because having python 2.6 also installed, just "python" raises an error)_
I get a success message, then... I'm **unable to find the stream.ini file ^^'** I guess it's relative to pip, but I don't find any helpful keyword for Google...

Besides, if i'm right pip only fetches packages we can then use in Python, thus why the usage of "WebcamLivestream" in documentation does not look like a Python function ? **Where to use it ?** If I run it into the bash, I obviously get a "command not found"...

### Thousands thanks !

DreamGoAndHaveFun

**Comment by scivision** [comment]
Hmm, I think I need to improve the PyPi package, this is in planning. However I'm not sure when I can get to it, it may be a few weeks. Thanks for reporting!

**Comment by dreamGoAndHaveFun** [comment]
Cool !
No problem :)

Do you have any workaround meanwhile ?

**Comment by scivision** [comment]
I would install the development version via Git:
```sh
git clone https://github.com/scivision/pylivestream

cd pylivestream

pip install -e .
```

**Comment by scivision** [comment]
This was fixed by https://github.com/scivision/PyLivestream/releases/tag/v1.9.2
