### ISSUE TITLE
ENH: audio-only streaming 

### ISSUE THREAD

**Issue by RoConverse** [scivision/PyLivestream#29]
is there a way to stream without audio?

**Comment by scivision** [comment]
Video only without audio wasn't considered, but I can see this can be useful in some cases as a future enhancement. Thanks for asking!

**Comment by scivision** [comment]
I accidentally found this is possible with minimal code modifications. I will do this when I'm able. Thanks!

**Comment by scivision** [comment]
Enabled in https://github.com/scivision/PyLivestream/releases/tag/v1.9.3
