### ISSUE TITLE
[Question]How we can convert it to executable program with better UI?

### ISSUE THREAD

**Issue by usmansharif525** [scivision/PyLivestream#30]
How we can convert it to executable program with better UI so we don't need to run commands.
I want to convert it to .exe program

**Comment by RoConverse** [comment]
use pyqt4 for ui and auto-py-to-exe to convert it to an exe file

**Comment by scivision** [comment]
If I understand the question correctly, this could be simply done by creating a .bat file (assuming you're running Windows) with the desired command line inside. Say you wanted to stream your Webcam to Periscope, make `webcamPeriscope.bat` containing:

```batch
python Webcam.py periscope --yes
```

Good luck!
