### ISSUE TITLE
Facebook Live: FFmpeg RTMPS error messages

### ISSUE THREAD

**Issue by josev814** [scivision/PyLivestream#31]
I was able to successfully stream to YouTube, but when trying to stream to Facebook it fails.  I updated the api url to be **rtmps://live-api-s.facebook.com:443/rtmp/**, since 80 is deprecated.  When trying to stream to facebook I get the following issues.

This message repeats a couple times, and then hits 100% of size for rfbufsize and keeps repeating.
`[dshow @ 000001d3f3a5c4a0] real-time buffer [Microphone (Realtek High Definition Audio)] [audio input] too full or near too full (63% of size: 3041280 [rtbufsize parameter])! frame dropped!`

When stopping the process I get these errors which seem to pertain to the additional query string parameters that facebook provides with it's streaming key:
`[tls @ 000001d3f74cbc60] Unable to read from socket
[tls @ 000001d3f74cbc60] Failed to send close message
rtmps://live-api-s.facebook.com:443/rtmp/150700682599743?s_bl=1: I/O error
's_ps' is not recognized as an internal or external command,
operable program or batch file.
's_sml' is not recognized as an internal or external command,
operable program or batch file.
's_sw' is not recognized as an internal or external command,
operable program or batch file.
's_vt' is not recognized as an internal or external command,
operable program or batch file.
'a' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by scivision** [comment]
I am also seeing FFmpeg not working to Facebook now that RMTPS is mandatory. I will need to look further.

**Comment by scivision** [comment]
I see different symptoms from Linux and Windows

* Windows FFmpeg 4.1.3:  `[rtmps ..] ... Resource temporarily unavailable` and no video shown on site
* Ubuntu 18.04 FFmpeg 3.4.6 `[tls ...] ...  The specified session has been invalidated for some reason.` and a few seconds of video

This happens with just FFmpeg itself from the command line, so I'm tempted to think it's an FFmpeg issue, I've seen others on the web talking about this. Or maybe I'm missing a command line option.

**Comment by scivision** [comment]
This appears to be fixed by FFmpeg >= 4.2
