### ISSUE TITLE
Multi-Site Streaming

### ISSUE THREAD

**Issue by josev814** [scivision/PyLivestream#32]
When attempting to stream to multiple sites, the Screenshare.py script says it has the additional sites as unrecognized arguments. If I try to use a comma as a delimiter between the sites, it says it can't find the site.
`Screenshare.py facebook youtube
usage: Screenshare.py [-h] [-i INI] [-y] [site]
Screenshare.py: error: unrecognized arguments: youtube`

**Comment by scivision** [comment]
Yes this is an issue I see. I updated the command line parsers to accept like
```sh
python Screenshare.py youtube periscope
```
so that's now OK. However, there is still an issue with needed to enclose that part of the command line in quotes. I will look at this when I am able. Thanks!

**Comment by josev814** [comment]
When doing multi-site, could we have a flag that's passed prior to the sites?  something like --sites youtube,facebook,periscope.  Then it gets split with a comma delimiter, or with the site option allow it to be comma delimited.  That way we don't have to put quotes around the sites.

**Comment by scivision** [comment]
This was fixed in https://github.com/scivision/PyLivestream/releases/tag/v1.9.3

there isn't a need for quotes

**Comment by Ennorath** [comment]
> This was fixed in https://github.com/scivision/PyLivestream/releases/tag/v1.9.3
> 
> there isn't a need for quotes or commas

Can I stream on 2 different youtube stream keys in same time? How to realize it, put 2 streamkeys in youtube.key?
I need 2 youtube lives in same time on 2 different channels and 2 different videos. Please, help.

Thanks for PyLivestream
