### ISSUE TITLE
how to use PyLivestream

### ISSUE THREAD

**Issue by pzy2253999075** [scivision/PyLivestream#33]
@scivision Could you give me some simple demo code to show me how to send liveStream to rtmp server，thanks

**Comment by scivision** [comment]
This can be done via FFmpeg directly. This Python script is really a command-line generator for FFmpeg for popular sites. For your own specific RTMP server, maybe just use FFmpeg directly.

https://trac.ffmpeg.org/wiki/StreamingGuide
