### ISSUE TITLE
您好，我想问下gridigrf12调用不了，是怎么回事？ 

### ISSUE THREAD

**Issue by luochunxi** [scivision/PyLivestream#34]
gridigrf12调用不了，是怎么回事？
mag = mag = gridigrf12(t='2010-7-12',glat=65,glon=-148,alt_km=100)
print(mag)

我的邮件地址xi15110738723@outlook.com   或  15110738723@163.com

**Comment by scivision** [comment]
This is for https://github.com/space-physics/igrf12
