### ISSUE TITLE
Not enough Bitrate

### ISSUE THREAD

**Issue by Kwok6140** [scivision/PyLivestream#37]
Is it possible that we can manually change the bitrate?

**Comment by Kwok6140** [comment]
Nevermind I edit the code and changed it

**Comment by scivision** [comment]
I think that would be fine. I only made the bitrate a lookup so I wouldn't have to remember. However there's no reason not to make it user definable. Thanks

**Comment by scivision** [comment]
oh, this is a per-site option `video_kbps`. It was already in the program I just didn't document it (I did now).
