### ISSUE TITLE
Video Resolution on Youtube

### ISSUE THREAD

**Issue by Puyodead1** [scivision/PyLivestream#38]
How can I increase the video resolution when streaming from an mp4 file? currently it's 360p and I would like to increase it to 1080p at most or 720p at least

**Comment by gauravniltech** [comment]
change it in pylivestream.ini
webcam_res: 1270x720 for 720p 
works for me

**Comment by Puyodead1** [comment]
I’ll try it out, thanks

**Comment by scivision** [comment]
Yes that's correct: webcam_res setting

**Comment by vandit2209** [comment]
@Puyodead1 can you please post your code and stream.ini file. I am not able to stream the video to YouTube.
Is it also necessary to have a streaming software like obs along with it?

**Comment by leothewolf** [comment]
> How can I increase the video resolution when streaming from an mp4 file? currently it's 360p and I would like to increase it to 1080p at most or 720p at least

Hey can you pls relay the code you used bcs am not able to make one? It would be very helpful of you if you do so
