### ISSUE TITLE
Unknown input format: '0:0'

### ISSUE THREAD

**Issue by cmccvic** [scivision/PyLivestream#4]
Hi I'm on a MacOS, after configure the youtube.key. I got the error of: Unknown input format: '0:0'.

I think it's a FFmpeg error?

I find from stream.ini, [darwin] there is a acap:0:0 how can I configure this one?

besides, I find from your description: where to configure the sys.platform specific parameters. in Stream.ini?

thank you so much!!

**Comment by scivision** [comment]
what do you get from:
```sh
ffmpeg -f avfoundation -list_devices true -i ""
```

this will tell what device index your desktop is at. The code may need to be refactored a bit to handle MacOS and Windows better, I primarily use Linux.
