### ISSUE TITLE
Dynamic Overlay using browser source or updating png?

### ISSUE THREAD

**Issue by dropitlikecross** [scivision/PyLivestream#43]
Is there a way to add dynamic overlay as either a browser source/html or a png that updates every # seconds?

**Comment by scivision** [comment]
This is not a use case i considered, though it is a common one.

**Comment by scivision** [comment]
It looks to me like this would require yet another program to drive FFmpeg in this fashion. PyLivestream is meant to just be a minimal command line generator for FFmpeg. And that other people happened to find useful too despite its narrow scope.
