### ISSUE TITLE
how can we do HTML overlay on webcam feed

### ISSUE THREAD

**Issue by gauravniltech** [scivision/PyLivestream#44]
I can do HTML to image conversion and then merge them using OpenCV but I want the CSS animation too # #43 #

**Comment by scivision** [comment]
This might be done via FFMPEG [subtitles](https://ffmpeg.org/ffmpeg-filters.html#subtitles). Since PyLivestream is really just a command-line generator, take the command from PyLivestream and try manually adding subtitle FFmpeg options to tat

**Comment by dropitlikecross** [comment]
Doesn't the file need to be .srt for subtitiles?

**Comment by scivision** [comment]
This looks to actually be outside the capabilities of FFmpeg without some substantial additional effort.
