### ISSUE TITLE
PyLivestream requires Python '>=3.5' but the running Python is 2.7.16

### ISSUE THREAD

**Issue by NEWUSS** [scivision/PyLivestream#48]
I always get the following message:
**PyLivestream requires Python '>=3.5' but the running Python is 2.7.16**

Does anyone know what I can do about it?

**Comment by scivision** [comment]
I'm not sure. This might be an old version of PyLivestream as at least python 3.6 is required. I would try running either

```sh
pip install -U PyLivestream
```

Or clone this repo and from the PyLivestream/ directory type

```sh
python3 setup.py develop --user
```
