### ISSUE TITLE
Support instagram

### ISSUE THREAD

**Issue by omidraha** [scivision/PyLivestream#57]

**Comment by scivision** [comment]
Thank you I will look into this, I appreciate your request.

**Comment by scivision** [comment]
It appears Instagram uses dynamic RTMP URLs, unlike most other streaming services. [Yellow Duck](https://yellowduck.tv/) returns the URL and stream key. This would have to be entered at the command line.

I haven't used Yellow Duck, but I think a workaround for this would be to use Pylivestream as if you were going to stream on Facebook, then copy and paste the FFMPEG command line into  a text editor. Use Yellow Duck to get the URL and stream key, and replace the Facebook RTMP URL with the Instagram URL.

I don't think that can be automated with PyLivestream. So to stream with Instagram, perhaps Yellow Duck with OBS would work better.
