### ISSUE TITLE
Getting Live Comment/chat

### ISSUE THREAD

**Issue by Nesslax** [scivision/PyLivestream#61]
Hello, 

I am wondering since it's a multi-live platform is it possible to have some function to get all platforms chat ? 

Thanks

**Comment by scivision** [comment]
That would be outside what this program does, which is to print out an FFmpeg command to start a stream using FFmpeg. This would be a feature of an aggregation service like StreamLabs.

**Comment by scivision** [comment]
Thanks for reaching out!
