### ISSUE TITLE
Input image needs to have even height/width

### ISSUE THREAD

**Issue by HarukiGrande** [scivision/PyLivestream#7]
Command: `python3.6 /usr/local/bin/FileGlobLivestream.py youtube /music/ogg/vaporwave "*.ogg" -image vape.png -loop`

Error:
```
[swscaler @ 0x29e1e60] deprecated pixel format used, make sure you did set range correctly
[libx264 @ 0x264a740] height not divisible by 2 (580x387)
Output #0, flv, to 'rtmp://a.rtmp.youtube.com/live2/[key]':
    Stream #0:0: Video: h264, none, q=2-31, 128 kb/s, SAR 1:1 DAR 0:0, 25 fps
    Metadata:
      encoder         : Lavc56.60.100 libx264
    Stream #0:1(und): Audio: aac, 0 channels, 128 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (mjpeg (native) -> h264 (libx264))
  Stream #1:0 -> #0:1 (vorbis (native) -> aac (native))
Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
Traceback (most recent call last):
  File "/usr/local/bin/FileGlobLivestream.py", line 65, in <module>
    playonce(flist, P.image, P.site, inifn, P.yes)
  File "/usr/local/bin/FileGlobLivestream.py", line 23, in playonce
    s.golive()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 121, in golive
    self.stream.golive()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 49, in golive
    sp.check_call(self.cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/ffmpeg', '-loop', '1', '-i', 'vape.png', '-i', '/music/ogg/vaporwave/Phoenix_#2772_-_ａ\xa0_ｇｉｒｌ\xa0_ｌｉｋｅ\xa0_ｙｏｕ-d7XN705TW68.ogg', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-tune', 'stillimage', '-c:a', 'aac', '-b:a', '128k', '-ar', '44100', '-threads', '0', '-shortest', '-strict', 'experimental', '-f', 'flv', 'rtmp://a.rtmp.youtube.com/live2/[key]']' returned non-zero exit status 1.
```

Changed image dimensions to 580x390 and the stream started, which then caused warnings to flag up on YouTube and lag every second: `Your encoder is sending data faster than realtime (multipleseconds of video each second). You must rate limit your livevideo upload to approximately 1 second of video each second.`

**Comment by scivision** [comment]
Yes I (well you first) found that the parameters were not optimal for audio broadcasts, I was too aggressive about conserving bandwidth. 
I wanted to allow those who stream music etc. to save data bandwidth with still images.
With the new settings, data bandwidth is still saved

[https://www.periscope.tv/scivision/1rmxPmowaYYKN](Example audio-only broadcast) with still mage using new code.

**Comment by HarukiGrande** [comment]
Thanks for fixing the issue quickly!
I'll test it on my end once the pip package has been updated.

**Comment by HarukiGrande** [comment]
The stream restarts every 5 or so seconds and it still cuts out every second on YT.

```
Press [q] to stop, [?] for help
[flv @ 0x16c2a80] Failed to update header with correct duration.te= 392.8kbits/s
[flv @ 0x16c2a80] Failed to update header with correct filesize.
frame= 6013 fps=310 q=-1.0 Lsize=   11526kB time=00:04:00.52 bitrate= 392.6kbits/s
video:7461kB audio:3776kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 2.576102%
```

**Comment by scivision** [comment]
Hmm, it must be something with a file vs. microphone, something in the transposing maybe. Do you have an example .ogg file to share? 
I.e. I have .ogg files, but maybe there is something different with your files.

**Comment by HarukiGrande** [comment]
https://harukigrande.com/tmp/example.ogg

I only have ogg files so I can't test with anything else at the moment.

**Comment by HarukiGrande** [comment]
All ogg files were obtained with `youtube-dl --add-metadata --extract-audio --audio-format vorbis [playlist link] -v -i`, so I don't exactly know what the quality of the files are.

**Comment by scivision** [comment]
tested with your example.ogg at [Periscope](https://www.periscope.tv/w/1jMJgqBYaEYKL) on a modest, wired internet connection. Looped a few times. When song restarts/changes, video goes black momentarily (due to FFmpeg).
I didn't initially hear any dropouts.
Per the Periscope servers, I had:
* video bitrate 250 kbps
* framerate 25 fps
* keyframe 2.4 sec
* audio bitrate 64 kbps

**Comment by scivision** [comment]
A few thoughts:
* live streaming in general takes a very low error rate internet connection. You might stream 1080p Netflix fine, due to buffering, but there could be hidden quality issue that Livestreaming in general shows. Do you have any issues with Skype / Duo / FaceTime quality?
* HD livestreaming with FFmpeg takes nearly 100% CPU (multi-core) to boost quality. I use 5 year old laptops typically when streaming with this program, Intel Core i5 / i7

**Comment by HarukiGrande** [comment]
http://www.speedtest.net/result/7354811017.png

Ubuntu 16.04 / dual Intel Xeon 5520 8 cores, 16 threads (average 7% usage) / ffmpeg 2.8.14

Didn't realise ffmpeg wasn't updated to the latest, so will try after doing that to see if it affects it.

**Comment by HarukiGrande** [comment]
Now I'm getting this again: `12:36 PM Bad Check video settings
Your encoder is sending data faster than realtime (multiple seconds of video each second). You must rate limit your live video upload to approximately 1 second of video each second.`

And the other issues are still appearing.

**Comment by HarukiGrande** [comment]
I let it stream for around 5 minutes, with it still restarting every few seconds, and this popped up:
```
Traceback (most recent call last): 2506kB time=00:00:50.68 bitrate= 405.1kbits/s speed=9.19x
  File "/usr/local/bin/FileGlobLivestream.py", line 65, in <module>
    playonce(flist, P.image, P.site, inifn, P.yes)
  File "/usr/local/bin/FileGlobLivestream.py", line 23, in playonce
    s.golive()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 145, in golive
    self.stream.golive()
  File "/usr/local/lib/python3.6/dist-packages/PyLivestream/__init__.py", line 50, in golive
    sp.check_call(self.cmd)
  File "/usr/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/ffmpeg', '-loop', '1', '-i', 'vape.png', '-i', '/music/ogg/nightcore/♫_DESPACITO_✘_Cover_✘_Remix_♫_(NIGHTCORE_MINIMIX)-L9ELICMnuIw.ogg', '-c:v', 'libx264', '-pix_fmt', 'yuv420p', '-preset', 'ultrafast', '-b:v', '500k', '-g', '60.0', '-c:a', 'aac', '-b:a', '128k', '-ar', '44100', '-threads', '0', '-shortest', '-strict', 'experimental', '-f', 'flv', 'rtmp://a.rtmp.youtube.com/live2/[key]']' died with <Signals.SIGSEGV: 11>.
```

**Comment by HarukiGrande** [comment]
`ffmpeg -re -loop 1 -framerate 2 -i "vape.png" -i "music_file.ogg" -c:a aac -s 2560x1440 -ab 128k -vcodec libx264 -pix_fmt yuv420p -maxrate 2048k -bufsize 2048k -framerate 30 -g 2 -strict experimental -f flv rtmp://a.rtmp.youtube.com/live2/[key]`

With the above command the stream doesn't cut out at all, but the bitrate is averaging at around 1320kbps and the speed started at 0.4x but had gradually climbed up to 0.94x  within minutes of the stream starting. 

```
YouTube is not receiving enough video to maintain smooth streaming. As such, viewers will experience buffering.
The stream's current bitrate (1338.00 Kbps) is lower than the recommended bitrate. We recommend that you use a stream bitrate of 9500 Kbps.
The stream's current bitrate (1338.00 Kbps) is lower than the recommended bitrate. We recommend that you use a stream bitrate of 9500 Kbps.```

I'm getting a quality of 1440p and it's evening out with speed.

**Comment by scivision** [comment]
It seems the issue may have been improper throttling, I was not computing the throttling for file inputs correctly. 
This has been resolved by https://github.com/scivision/PyLivestream/releases/tag/v1.6.5
so that hardware devices (microphones, webcams, screen capture) are throttled by hardware, while files are software throttled. This makes a big CPU load reduction and should hopefully fix most/all of the issues above.

**Comment by HarukiGrande** [comment]
Alright, I'll test this release out once the pip package is sorted :D

**Comment by HarukiGrande** [comment]
It's streaming without any cutting out now :D 

https://www.youtube.com/channel/UCBMH7T0pVSObdvPoQ0aQ09Q/live

The only issue I notice is that I'm using a 1920x1080 image to set the YT quality at 1080p but this is causing YT to show `Video output low` statuses:
```
6:32 PM OK Video output low
The stream's current bitrate (433.00 Kbps) is lower than the recommended bitrate. We recommend that you use a stream bitrate of 4500 Kbps.
```

**Comment by scivision** [comment]
That low bandwidth for static image may be fine. It would be kind of wasteful to burn up your clients' bandwidth 10x more than necessary for a static image.

**Comment by scivision** [comment]
Periscope gives even more detailed feedback on stream quality without having to actually go live. That is, in Periscope stream preview you see your own video with a dozen technical parameters measured with specific feedback for optimization.

YouTube and Periscope are tolerant of a wide range of inputs. Facebook is pretty picky on the other hand.

**Comment by HarukiGrande** [comment]
Had an FB stream running for the past hour successfully with the same args as I used for YT, and just downsized the image to 854x480. Everything is working as expected 👍

**Comment by scivision** [comment]
Great, as far as services I've tried, Facebook is the hardest to get RTMP accepted so excellent.

**Comment by HarukiGrande** [comment]
![hmjpslm 1](https://user-images.githubusercontent.com/22057153/40811826-c1f83276-652a-11e8-84a3-d5e6bdcdedf2.png)

Modified playonce() to add the audio file metadata to the image as an overlay as I was bored, and that's working on FB :D 

```py
def playonce(flist: List[Path], image: Path, site: str, inifn: Path,
             yes: bool):
    
    random.shuffle(flist)

    for f in flist:
        data = TinyTag.get(str(f))
        title = data.title
        img = Image.open(str(image))
        w, h = img.size
        box = Image.new("RGBA", (w,int(h/5)), (146,147,180, 200))
        boxw, boxh = box.size
        draw = ImageDraw.Draw(box)
        font = ImageFont.truetype("/root/fonts/dejavu.ttf", 24)
        tw, th = draw.textsize(title, font=font)
        draw.text(((boxw-tw)/2, (boxh-th)/2), title, font=font, fill="black")
        img.paste(box, (0, h-boxh), mask=box)
        img.save("temp-pylive.jpg")
        tmp = "temp-pylive.jpg"
        s = PyLivestream.FileIn(inifn, site, infn=f, loop=False, image=tmp,
                                yes=yes)

        s.golive()
```

**Comment by scivision** [comment]
Yes this is part of the program now, FFmpeg can draw the text on the video without PIL:

https://github.com/scivision/PyLivestream/blob/master/PyLivestream/ffmpeg.py#L30
